# Hate crime

In [1]:
import pandas as pd

## Real Dataset - Hate crime

In [6]:
df_real_dataset = pd.read_csv('./real_datasets/criminal_justice/preproccesed/hate_crime_preproccesed.csv')

In [7]:
df_real_dataset

,data_year,agency_type_name,state_abbr,state_name,incident_date,adult_victim_count,juvenile_victim_count,total_offender_count,adult_offender_count,juvenile_offender_count,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,location_name,bias_desc,victim_types,multiple_offense,multiple_bias
0,1991,City,AR,Arkansas,1991-07-04,NaN,NaN,1,NaN,NaN,Black or African American,Not Specified,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
1,1991,City,AR,Arkansas,1991-12-24,NaN,NaN,1,NaN,NaN,Black or African American,Not Specified,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
2,1991,City,AR,Arkansas,1991-07-10,NaN,NaN,1,NaN,NaN,Black or African American,Not Specified,2,Aggravated Assault;Murder and Nonnegligent Man...,2.0,Residence/Home,Anti-White,Individual,M,S
3,1991,City,AR,Arkansas,1991-10-06,NaN,NaN,2,NaN,NaN,Black or African American,Not Specified,1,Intimidation,1.0,Residence/Home,Anti-White,Individual,S,S
4,1991,County,AR,Arkansas,1991-10-14,NaN,NaN,1,NaN,NaN,White,Not Specified,1,Intimidation,1.0,School/College,Anti-Black or African American,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265829,2024,City,WY,Wyoming,2024-10-18,1.0,0.0,0,NaN,NaN,Not Specified,Not Specified,1,Destruction/Damage/Vandalism of Property,1.0,Residence/Home,Anti-Gay (Male),Individual,S,S
265830,2024,City,WY,Wyoming,2024-11-11,0.0,0.0,0,NaN,NaN,Not Specified,Not Specified,1,Destruction/Damage/Vandalism of Property,0.0,Arena/Stadium/Fairgrounds/Coliseum,Anti-Other Christian,Business,S,S
265831,2024,City,WY,Wyoming,2024-12-12,1.0,0.0,0,NaN,NaN,Not Specified,Not Specified,2,Destruction/Damage/Vandalism of Property;Intim...,1.0,Residence/Home,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,M,S
265832,2024,University or College,WY,Wyoming,2024-11-18,0.0,0.0,0,NaN,NaN,Not Specified,Not Specified,1,Destruction/Damage/Vandalism of Property,0.0,School-College/University,Anti-Jewish,Government,S,S
265833,2024,University or College,WY,Wyoming,2024-11-27,1.0,0.0,0,NaN,NaN,Not Specified,Not Specified,1,Destruction/Damage/Vandalism of Property,1.0,School-College/University,Anti-Gay (Male),Individual,S,S

In [9]:
df_real_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265834 entries, 0 to 265833
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   data_year                 265834 non-null  int64
 1   agency_type_name          265834 non-null  object
 2   state_abbr                265834 non-null  object
 3   state_name                265834 non-null  object
 4   incident_date             265834 non-null  object
 5   adult_victim_count        94429 non-null   float64
 6   juvenile_victim_count     91644 non-null   float64
 7   total_offender_count      265834 non-null  int64
 8   adult_offender_count      81967 non-null   float64
 9   juvenile_offender_count   81960 non-null   float64
 10  offender_race             265834 non-null  object
 11  offender_ethnicity        265834 non-null  object
 12  victim_count              265834 non-null  int64
 13  offense_name              265834 non-null  object
 14  total_individual_victims  260560 non-null  float64
 15  location_name             265834 non-null  object
 16  bias_desc                 265834 non-null  object
 17  victim_types              265834 non-null  object
 18  multiple_offense          265834 non-null  object
 19  multiple_bias             265834 non-null  object
dtypes: float64(5), int64(3), object(12)
memory usage: 40.6+ MB

In [11]:
df_real_dataset.shape

(265834, 20)

In [12]:
df_real_dataset.describe()

,data_year,adult_victim_count,juvenile_victim_count,total_offender_count,adult_offender_count,juvenile_offender_count,victim_count,total_individual_victims
count,265834.000000,94429.000000,91644.000000,265834.000000,81967.000000,81960.000000,265834.000000,260560.000000
mean,2008.447516,0.765866,0.110722,0.946440,0.641417,0.137933,1.017432,0.990367
std,10.152622,1.051430,0.499200,1.284311,0.798185,0.562211,0.250140,1.117459
min,1991.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,2008.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
75%,2018.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,2024.000000,146.000000,60.000000,99.000000,60.000000,30.000000,5.000000,147.000000

In [14]:
df_real_dataset.isnull().sum()

data_year                        0
agency_type_name                 0
state_abbr                       0
state_name                       0
incident_date                    0
adult_victim_count          171405
juvenile_victim_count       174190
total_offender_count             0
adult_offender_count        183867
juvenile_offender_count     183874
offender_race                    0
offender_ethnicity               0
victim_count                     0
offense_name                     0
total_individual_victims      5274
location_name                    0
bias_desc                        0
victim_types                     0
multiple_offense                 0
multiple_bias                    0
dtype: int64

## Real Dataset - Hate crime - Zero Shot

In [15]:
df_zero_shot = pd.read_csv('./generated_datasets/criminal_justice/GPT-5/hate_crime_zero_shot.csv')

In [16]:
df_zero_shot

,data_year,agency_type_name,state_abbr,state_name,incident_date,adult_victim_count,juvenile_victim_count,total_offender_count,adult_offender_count,juvenile_offender_count,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,location_name,bias_desc,victim_types,multiple_offense,multiple_bias
0,1991,City,GA,Georgia,1991-11-19,1,0,1,0,0,White,Not Hispanic or Latino,2,Simple Assault,1,Bar/Nightclub,Anti-Black or African American,Other,False,False
1,1991,County,SD,South Dakota,1991-11-24,2,0,1,1,0,White,Hispanic or Latino,2,Simple Assault,2,Church/Synagogue/Temple/Mosque,Anti-Black or African American,Individual,False,False
2,1991,City,IL,Illinois,1991-02-11,0,0,1,0,0,White,Not Hispanic or Latino,1,Aggravated Assault,0,Residence/Home,Anti-Black or African American,Government,False,False
3,1991,City,OR,Oregon,1991-06-10,0,0,1,1,0,White,Hispanic or Latino,1,Intimidation,0,Highway/Road/Alley,Anti-Jewish,Individual,False,False
4,1991,County,MI,Michigan,1991-07-17,0,0,2,2,0,Black or African American,Unknown,1,Aggravated Assault,0,Church/Synagogue/Temple/Mosque,Anti-Jewish,Other,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,2014,Other,TN,Tennessee,2014-12-16,2,1,1,0,1,White,Not Hispanic or Latino,4,Intimidation,3,Highway/Road/Alley,Anti-Jewish,Business,False,False
507,2014,County,WV,West Virginia,2014-02-02,0,0,1,1,0,Unknown,Not Hispanic or Latino,1,Simple Assault,0,Bar/Nightclub,Anti-Hispanic or Latino,Other;Society/Public,True,False
508,2014,City,MS,Mississippi,2014-04-09,2,0,1,0,1,White,Not Hispanic or Latino,2,Arson,2,Government/Public Building,Anti-Black or African American,Individual,False,False
509,2014,University/College,MS,Mississippi,2014-01-22,0,0,1,1,0,White,Hispanic or Latino,1,Aggravated Assault,0,Parking Lot/Garage,Anti-Jewish,Religious Organization,False,False
510,2014,City,CA,California,2014-03-12,3,0,1,0,0,White,Not Hispanic or Latino,4,Destruction/Damage/Vandalism of Property,3,Church/Synagogue/Temple/Mosque,Anti-White,Business,True,False

In [19]:
df_zero_shot.shape

(511, 20)

In [20]:
df_zero_shot.describe()

,data_year,adult_victim_count,juvenile_victim_count,total_offender_count,adult_offender_count,juvenile_offender_count,victim_count,total_individual_victims
count,511.000000,511.000000,511.000000,511.000000,511.000000,511.000000,511.000000,511.000000
mean,2002.665362,1.117417,0.140900,1.248532,0.841487,0.086106,2.150685,1.258317
std,6.992962,0.931955,0.370096,0.503783,0.743812,0.280795,1.020762,1.011601
min,1991.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,1996.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,2003.000000,1.000000,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000
75%,2009.000000,2.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000
max,2014.000000,4.000000,2.000000,4.000000,3.000000,1.000000,5.000000,4.000000

In [21]:
df_zero_shot.isnull().sum()

data_year                   0
agency_type_name            0
state_abbr                  0
state_name                  0
incident_date               0
adult_victim_count          0
juvenile_victim_count       0
total_offender_count        0
adult_offender_count        0
juvenile_offender_count     0
offender_race               0
offender_ethnicity          0
victim_count                0
offense_name                0
total_individual_victims    0
location_name               0
bias_desc                   0
victim_types                0
multiple_offense            0
multiple_bias               0
dtype: int64

## Real Dataset - Hate crime - One Shot

In [22]:
df_one_shot = pd.read_csv('./generated_datasets/criminal_justice/GPT-5/hate_crime_one_shot.csv')

In [23]:
df_one_shot.shape

(467, 20)

In [24]:
df_one_shot.describe

<bound method NDFrame.describe of      data_year    agency_type_name state_abbr   state_name incident_date  \
0         1991                City         AR     Arkansas    1991-07-04
1         1991                City         DE     Delaware    1991-05-21
2         1991              County         HI       Hawaii    1991-06-24
3         1991              County         MS  Mississippi    1991-12-27
4         1991        State Police         OH         Ohio    1991-03-25
..         ...                 ...        ...          ...           ...
462       2014                City         CO     Colorado    2014-11-18
463       2014              County         LA    Louisiana    2014-03-05
464       2014  University/College         VA     Virginia    2014-02-27
465       2014              County         MD     Maryland    2014-05-27
466       2014  University/College         NM   New Mexico    2014-02-27

     adult_victim_count  juvenile_victim_count  total_offender_count  \
0                   NaN                    NaN                   1.0
1                   2.0                    0.0                   1.0
2                   2.0                    1.0                   1.0
3                   0.0                    1.0                   1.0
4                   4.0                    NaN                   1.0
..                  ...                    ...                   ...
462                 3.0                    0.0                   1.0
463                 0.0                    1.0                   1.0
464                 0.0                    1.0                   1.0
465                 0.0                    1.0                   1.0
466                 1.0                    0.0                   1.0

     adult_offender_count  juvenile_offender_count              offender_race  \
0                     NaN                      NaN  Black or African American
1                     1.0                      0.0                      Asian
2                     1.0                      0.0                      Asian
3                     0.0                      1.0                      White
4                     0.0                      1.0                      White
..                    ...                      ...                        ...
462                   1.0                      0.0                      White
463                   1.0                      0.0  Black or African American
464                   1.0                      0.0                      White
465                   1.0                      0.0                      White
466                   0.0                      1.0                    Unknown

     offender_ethnicity  victim_count        offense_name  \
0         Not Specified             1  Aggravated Assault
1               Unknown             2        Intimidation
2    Hispanic or Latino             3  Aggravated Assault
3    Hispanic or Latino             1               Arson
4    Hispanic or Latino             4        Intimidation
..                  ...           ...                 ...
462  Hispanic or Latino             3        Intimidation
463  Hispanic or Latino             1  Aggravated Assault
464  Hispanic or Latino             1      Simple Assault
465             Unknown             1        Intimidation
466       Not Specified             1      Simple Assault

     total_individual_victims               location_name  \
0                         1.0              Residence/Home
1                         2.0              Residence/Home
2                         3.0              Residence/Home
3                         1.0          Parking Lot/Garage
4                         4.0          Parking Lot/Garage
..                        ...                         ...
462                       3.0          Parking Lot/Garage
463                       1.0                  Restaurant
464                       0.0              School/College
465                       0.0  Government/Public Building
466                       1.0              Residence/Home

                          bias_desc    victim_types multiple_offense  \
0    Anti-Black or African American      Individual                S
1    Anti-Black or African American      Individual                S
2           Anti-Hispanic or Latino      Individual                N
3           Anti-LGBT (Mixed Group)      Individual                N
4                   Anti-Gay (Male)      Individual                S
..                              ...             ...              ...
462         Anti-LGBT (Mixed Group)      Individual                S
463                     Anti-Jewish      Individual                S
464  Anti-Black or African American  Society/Public                S
465                    Anti-Lesbian        Business                S
466                 Anti-Gay (Male)      Individual                N

    multiple_bias
0               S
1               S
2               S
3               N
4               N
..            ...
462             N
463             S
464             S
465             S
466             N

[467 rows x 20 columns]>

In [25]:
df_one_shot.isnull().sum()

data_year                    0
agency_type_name             0
state_abbr                   0
state_name                   0
incident_date                0
adult_victim_count          25
juvenile_victim_count       27
total_offender_count        30
adult_offender_count        35
juvenile_offender_count     24
offender_race                0
offender_ethnicity           0
victim_count                 0
offense_name                 0
total_individual_victims     0
location_name                0
bias_desc                    0
victim_types                 0
multiple_offense             0
multiple_bias                0
dtype: int64

## Real Dataset - Hate crime - Few Shot

In [27]:
df_few_shot = pd.read_csv('./generated_datasets/criminal_justice/GPT-5/hate_crime_few_shot.csv')

In [28]:
df_few_shot.shape

(539, 20)

In [29]:
df_few_shot.describe

<bound method NDFrame.describe of      data_year    agency_type_name state_abbr      state_name incident_date  \
0         1991                City         AR        Arkansas    1991-07-04
1         1991                City         AR        Arkansas    1991-12-24
2         1991                City         AR        Arkansas    1991-07-10
3         1991                City         AR        Arkansas    1991-10-06
4         1991              County         MA   Massachusetts    1991-07-22
..         ...                 ...        ...             ...           ...
534       2014        State Police         WV   West Virginia    2014-09-11
535       2014        State Police         SC  South Carolina    2014-04-16
536       2014              County         WV   West Virginia    2014-11-15
537       2014                City         MS     Mississippi    2014-01-30
538       2014  University/College         MI        Michigan    2014-01-17

     adult_victim_count  juvenile_victim_count  total_offender_count  \
0                   NaN                    NaN                   1.0
1                   NaN                    NaN                   1.0
2                   NaN                    NaN                   1.0
3                   NaN                    NaN                   2.0
4                   0.0                    1.0                   NaN
..                  ...                    ...                   ...
534                 0.0                    3.0                   2.0
535                 2.0                    0.0                   3.0
536                 1.0                    0.0                   3.0
537                 0.0                    2.0                   1.0
538                 1.0                    0.0                   3.0

     adult_offender_count  juvenile_offender_count  \
0                     NaN                      NaN
1                     NaN                      NaN
2                     NaN                      NaN
3                     NaN                      NaN
4                     0.0                      3.0
..                    ...                      ...
534                   1.0                      1.0
535                   0.0                      3.0
536                   0.0                      NaN
537                   0.0                      1.0
538                   3.0                      0.0

                        offender_race      offender_ethnicity  victim_count  \
0           Black or African American           Not Specified             1
1           Black or African American           Not Specified             2
2           Black or African American           Not Specified             2
3           Black or African American           Not Specified             1
4                               White  Not Hispanic or Latino             1
..                                ...                     ...           ...
534                             Asian  Not Hispanic or Latino             3
535  American Indian or Alaska Native  Not Hispanic or Latino             2
536         Black or African American  Not Hispanic or Latino             1
537                           Unknown                 Unknown             2
538                             White  Not Hispanic or Latino             1

                                          offense_name  \
0                                   Aggravated Assault
1    Aggravated Assault;Destruction/Damage/Vandalis...
2    Aggravated Assault;Murder and Nonnegligent Man...
3                                         Intimidation
4    Aggravated Assault;Destruction/Damage/Vandalis...
..                                                 ...
534                                              Arson
535                                            Robbery
536                                Motor Vehicle Theft
537                        Intimidation;Simple Assault
538                                            Robbery

     total_individual_victims                       location_name  \
0                         1.0                      Residence/Home
1                         1.0  Highway/Road/Alley/Street/Sidewalk
2                         2.0                      Residence/Home
3                         1.0                      Residence/Home
4                         1.0                          Restaurant
..                        ...                                 ...
534                       3.0                       Bar/Nightclub
535                       0.0                       Bar/Nightclub
536                       0.0  Highway/Road/Alley/Street/Sidewalk
537                       0.0  Highway/Road/Alley/Street/Sidewalk
538                       0.0          Commercial/Office Building

                          bias_desc    victim_types multiple_offense  \
0    Anti-Black or African American      Individual                S
1                        Anti-White      Individual                M
2                        Anti-White      Individual                M
3                        Anti-White      Individual                S
4                        Anti-Asian      Individual                M
..                              ...             ...              ...
534         Anti-Hispanic or Latino      Individual                S
535  Anti-Black or African American        Business                S
536                     Anti-Muslim           Other                S
537         Anti-Hispanic or Latino        Business                M
538                 Anti-Protestant  Society/Public                S

    multiple_bias
0               S
1               S
2               S
3               S
4               S
..            ...
534             S
535             S
536             N
537             S
538             S

[539 rows x 20 columns]>

In [30]:
df_few_shot.isnull().sum()

data_year                    0
agency_type_name             0
state_abbr                   0
state_name                   0
incident_date                0
adult_victim_count          64
juvenile_victim_count       57
total_offender_count        60
adult_offender_count        62
juvenile_offender_count     60
offender_race                0
offender_ethnicity           0
victim_count                 0
offense_name                 0
total_individual_victims     0
location_name                0
bias_desc                    0
victim_types                 0
multiple_offense             0
multiple_bias                0
dtype: int64