In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/raw/year_2024.csv")

/var/folders/26/qp1p5b3149b9hy747yzmh3bh0000gn/T/ipykernel_1412/3419199480.py:1: DtypeWarning: Columns (5,22,23,24,26,27,28,29,30,31,32,33,38,43,44,46,77,78,79,80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/raw/year_2024.csv")

In [3]:
df.head()

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2024,549300DD5QQUHO6PCH70,38060,AZ,4013.0,4013061031.0,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,6566,36.72,101300,115,1398,1733,14
1,2024,549300DD5QQUHO6PCH70,24780,NC,37147.0,37147001100.0,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,5082,27.88,84700,106,1555,2198,32
2,2024,549300DD5QQUHO6PCH70,29414,IN,18127.0,18127050602.0,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,4804,17.80,91100,122,1412,1736,39
3,2024,549300DD5QQUHO6PCH70,17900,SC,45063.0,45063020706.0,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2977,79.27,86300,62,734,1184,41
4,2024,549300DD5QQUHO6PCH70,36420,OK,40081.0,40081961402.0,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,4726,24.23,89100,94,1722,2135,26

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12229298 entries, 0 to 12229297
Data columns (total 99 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   activity_year                             int64
 1   lei                                       object
 2   derived_msa-md                            int64
 3   state_code                                object
 4   county_code                               float64
 5   census_tract                              object
 6   conforming_loan_limit                     object
 7   derived_loan_product_type                 object
 8   derived_dwelling_category                 object
 9   derived_ethnicity                         object
 10  derived_race                              object
 11  derived_sex                               object
 12  action_taken                              int64
 13  purchaser_type                            int64
 14  preapproval                               int64
 15  loan_type                                 int64
 16  loan_purpose                              int64
 17  lien_status                               int64
 18  reverse_mortgage                          int64
 19  open-end_line_of_credit                   int64
 20  business_or_commercial_purpose            int64
 21  loan_amount                               float64
 22  loan_to_value_ratio                       object
 23  interest_rate                             object
 24  rate_spread                               object
 25  hoepa_status                              int64
 26  total_loan_costs                          object
 27  total_points_and_fees                     object
 28  origination_charges                       object
 29  discount_points                           object
 30  lender_credits                            object
 31  loan_term                                 object
 32  prepayment_penalty_term                   object
 33  intro_rate_period                         object
 34  negative_amortization                     int64
 35  interest_only_payment                     int64
 36  balloon_payment                           int64
 37  other_nonamortizing_features              int64
 38  property_value                            object
 39  construction_method                       int64
 40  occupancy_type                            int64
 41  manufactured_home_secured_property_type   int64
 42  manufactured_home_land_property_interest  int64
 43  total_units                               object
 44  multifamily_affordable_units              object
 45  income                                    float64
 46  debt_to_income_ratio                      object
 47  applicant_credit_score_type               int64
 48  co-applicant_credit_score_type            int64
 49  applicant_ethnicity-1                     float64
 50  applicant_ethnicity-2                     float64
 51  applicant_ethnicity-3                     float64
 52  applicant_ethnicity-4                     float64
 53  applicant_ethnicity-5                     float64
 54  co-applicant_ethnicity-1                  float64
 55  co-applicant_ethnicity-2                  float64
 56  co-applicant_ethnicity-3                  float64
 57  co-applicant_ethnicity-4                  float64
 58  co-applicant_ethnicity-5                  float64
 59  applicant_ethnicity_observed              int64
 60  co-applicant_ethnicity_observed           int64
 61  applicant_race-1                          float64
 62  applicant_race-2                          float64
 63  applicant_race-3                          float64
 64  applicant_race-4                          float64
 65  applicant_race-5                          float64
 66  co-applicant_race-1                       float64
 67  co-applicant_race-2                       float64
 68  co-applicant_race-3                       float64
 69  co-applicant_race-4                       float64
 70  co-applicant_race-5                       float64
 71  applicant_race_observed                   int64
 72  co-applicant_race_observed                int64
 73  applicant_sex                             int64
 74  co-applicant_sex                          int64
 75  applicant_sex_observed                    int64
 76  co-applicant_sex_observed                 int64
 77  applicant_age                             object
 78  co-applicant_age                          object
 79  applicant_age_above_62                    object
 80  co-applicant_age_above_62                 object
 81  submission_of_application                 int64
 82  initially_payable_to_institution          int64
 83  aus-1                                     int64
 84  aus-2                                     float64
 85  aus-3                                     float64
 86  aus-4                                     float64
 87  aus-5                                     float64
 88  denial_reason-1                           int64
 89  denial_reason-2                           float64
 90  denial_reason-3                           float64
 91  denial_reason-4                           float64
 92  tract_population                          int64
 93  tract_minority_population_percent         float64
 94  ffiec_msa_md_median_family_income         int64
 95  tract_to_msa_income_percentage            int64
 96  tract_owner_occupied_units                int64
 97  tract_one_to_four_family_homes            int64
 98  tract_median_age_of_housing_units         int64
dtypes: float64(31), int64(40), object(28)
memory usage: 9.0+ GB

In [5]:
drop_cols = [
    "lei", "conforming_loan_limit", "purchaser_type", "preapproval", 
    "loan_type", "lien_status", "reverse_mortgage", 
    "open-end_line_of_credit", "business_or_commercial_purpose", 
    "applicant_ethnicity-2", "applicant_ethnicity-3", "applicant_ethnicity-4", "applicant_ethnicity-5",
    "co-applicant_ethnicity-2", "co-applicant_ethnicity-3", "co-applicant_ethnicity-4", "co-applicant_ethnicity-5",
    "applicant_race-2", "applicant_race-3", "applicant_race-4", "applicant_race-5",
    "co-applicant_race-2", "co-applicant_race-3", "co-applicant_race-4", "co-applicant_race-5",
    "aus-1","aus-2","aus-3","aus-4","aus-5",
    "denial_reason-1","denial_reason-2","denial_reason-3","denial_reason-4",
    "tract_population","tract_minority_population_percent","ffiec_msa_md_median_family_income",
    "tract_to_msa_income_percentage","tract_owner_occupied_units","tract_one_to_four_family_homes",
    "tract_median_age_of_housing_units"
]

In [6]:
df = df.drop(columns=drop_cols, errors="ignore")

In [7]:
df = df.replace(["", "NULL", "NaN", "NA"], pd.NA)

In [8]:
num_cols = ["loan_amount", "loan_to_value_ratio", "interest_rate", "property_value", "income", "debt_to_income_ratio"]
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [9]:
action_map = {
    1: "Loan originated",
    2: "Application approved but not accepted",
    3: "Application denied",
    4: "Application withdrawn",
    5: "File closed for incompleteness"
}
df["action_taken"] = df["action_taken"].map(action_map).fillna(df["action_taken"])

In [10]:
df.to_csv("../../data/preprocessed/year_2024_preprocessed.csv", index=False)

In [11]:
df_cleaned = pd.read_csv("../../data/preprocessed/year_2024_preprocessed.csv")

/var/folders/26/qp1p5b3149b9hy747yzmh3bh0000gn/T/ipykernel_1412/596415016.py:1: DtypeWarning: Columns (4,10,15,17,18,19,20,21,22,23,24,34,35,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cleaned = pd.read_csv("../../data/preprocessed/year_2024_preprocessed.csv")

In [12]:
df_cleaned

,activity_year,derived_msa-md,state_code,county_code,census_tract,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,...,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution
0,2024,38060,AZ,4013.0,4013061031.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,...,3,5,2,4,45-54,9999,No,NaN,1,1
1,2024,24780,NC,37147.0,37147001100.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,...,2,2,2,2,55-64,55-64,No,No,1,1
2,2024,29414,IN,18127.0,18127050602.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,...,1,5,2,4,25-34,9999,No,NaN,1,1
3,2024,17900,SC,45063.0,45063020706.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,...,1,2,2,2,45-54,45-54,No,No,1,1
4,2024,36420,OK,40081.0,40081961402.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,...,1,2,2,2,35-44,25-34,No,No,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12229293,2024,40420,IL,17201.0,17201000513.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Asian,Male,...,1,5,2,4,45-54,9999,No,NaN,1,1
12229294,2024,48680,FL,12119.0,12119911205.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,...,2,1,2,2,55-64,55-64,Yes,Yes,1,1
12229295,2024,99999,MS,28109.0,28109950202.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,...,1,2,2,2,45-54,35-44,No,No,1,1
12229296,2024,19340,IA,19163.0,19163011700.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,...,1,2,2,2,65-74,65-74,Yes,Yes,1,1
12229297,2024,18140,OH,39049.0,39049010204.0,VA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Male,...,1,5,2,4,25-34,9999,No,NaN,1,1

In [13]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12229298 entries, 0 to 12229297
Data columns (total 58 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   activity_year                             int64
 1   derived_msa-md                            int64
 2   state_code                                object
 3   county_code                               float64
 4   census_tract                              object
 5   derived_loan_product_type                 object
 6   derived_dwelling_category                 object
 7   derived_ethnicity                         object
 8   derived_race                              object
 9   derived_sex                               object
 10  action_taken                              object
 11  loan_purpose                              int64
 12  loan_amount                               float64
 13  loan_to_value_ratio                       float64
 14  interest_rate                             float64
 15  rate_spread                               object
 16  hoepa_status                              int64
 17  total_loan_costs                          object
 18  total_points_and_fees                     object
 19  origination_charges                       object
 20  discount_points                           object
 21  lender_credits                            object
 22  loan_term                                 object
 23  prepayment_penalty_term                   object
 24  intro_rate_period                         object
 25  negative_amortization                     int64
 26  interest_only_payment                     int64
 27  balloon_payment                           int64
 28  other_nonamortizing_features              int64
 29  property_value                            float64
 30  construction_method                       int64
 31  occupancy_type                            int64
 32  manufactured_home_secured_property_type   int64
 33  manufactured_home_land_property_interest  int64
 34  total_units                               object
 35  multifamily_affordable_units              object
 36  income                                    float64
 37  debt_to_income_ratio                      float64
 38  applicant_credit_score_type               int64
 39  co-applicant_credit_score_type            int64
 40  applicant_ethnicity-1                     float64
 41  co-applicant_ethnicity-1                  float64
 42  applicant_ethnicity_observed              int64
 43  co-applicant_ethnicity_observed           int64
 44  applicant_race-1                          float64
 45  co-applicant_race-1                       float64
 46  applicant_race_observed                   int64
 47  co-applicant_race_observed                int64
 48  applicant_sex                             int64
 49  co-applicant_sex                          int64
 50  applicant_sex_observed                    int64
 51  co-applicant_sex_observed                 int64
 52  applicant_age                             object
 53  co-applicant_age                          object
 54  applicant_age_above_62                    object
 55  co-applicant_age_above_62                 object
 56  submission_of_application                 int64
 57  initially_payable_to_institution          int64
dtypes: float64(11), int64(24), object(23)
memory usage: 5.3+ GB